name: Chunks Test
on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Env
        run: |
          echo "$GCP_SA_JSON" > sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json" >> $GITHUB_ENV
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib pandas python-dateutil requests
      - name: Run
        env:
          YOUTUBE_API_KEYS: ${{ secrets.YOUTUBE_API_KEYS }}
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
          SOURCE_SHEET_TAB: ${{ secrets.SOURCE_SHEET_TAB }}
          MAP_SHEET_TAB: ${{ secrets.MAP_SHEET_TAB }}
          CHUNKS_FOLDER_ID: ${{ secrets.CHUNKS_FOLDER_ID }}
          PLAYLIST_LIMIT: ${{ secrets.PLAYLIST_LIMIT }}
          ROWS_PER_DOC: ${{ secrets.ROWS_PER_DOC }}
          DRIVE_OAUTH_CLIENT_ID: ${{ secrets.DRIVE_OAUTH_CLIENT_ID }}
          DRIVE_OAUTH_CLIENT_SECRET: ${{ secrets.DRIVE_OAUTH_CLIENT_SECRET }}
          DRIVE_OAUTH_REFRESH_TOKEN: ${{ secrets.DRIVE_OAUTH_REFRESH_TOKEN }}
        run: |
          python scripts/chunk_sheets.py
