name: run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'   # ежедневный запуск 10:00 UTC

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Write SA key
        run: echo "$GCP_SA_JSON" > sa.json
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            google-api-python-client \
            google-auth \
            google-auth-httplib2 \
            google-auth-oauthlib \
            pandas \
            requests

      - name: OAuth probe
        env:
          DRIVE_OAUTH_CLIENT_ID: ${{ secrets.DRIVE_OAUTH_CLIENT_ID }}
          DRIVE_OAUTH_CLIENT_SECRET: ${{ secrets.DRIVE_OAUTH_CLIENT_SECRET }}
          DRIVE_OAUTH_REFRESH_TOKEN: ${{ secrets.DRIVE_OAUTH_REFRESH_TOKEN }}
        run: python scripts/oauth_probe.py

      - name: Run chunker
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
          YOUTUBE_API_KEYS: ${{ secrets.YOUTUBE_API_KEYS }}
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
          SOURCE_SHEET_TAB: ${{ secrets.SOURCE_SHEET_TAB }}
          MAP_SHEET_TAB: ${{ secrets.MAP_SHEET_TAB }}
          CHUNKS_FOLDER_ID: ${{ secrets.CHUNKS_FOLDER_ID }}
          PLAYLIST_LIMIT: ${{ secrets.PLAYLIST_LIMIT }}
          ROWS_PER_DOC: ${{ secrets.ROWS_PER_DOC }}
          DRIVE_OAUTH_CLIENT_ID: ${{ secrets.DRIVE_OAUTH_CLIENT_ID }}
          DRIVE_OAUTH_CLIENT_SECRET: ${{ secrets.DRIVE_OAUTH_CLIENT_SECRET }}
          DRIVE_OAUTH_REFRESH_TOKEN: ${{ secrets.DRIVE_OAUTH_REFRESH_TOKEN }}
        run: python scripts/chunk_sheets.py
